version: '3.8'
services:
  db:
    image: 'mysql:8.0'  
    container_name: coffee-shop-db 
    environment:
      MYSQL_ROOT_PASSWORD: Admin2  
      MYSQL_DATABASE: coffee_shop_backend    
      MYSQL_USER: myuser    
      MYSQL_PASSWORD: Admin1       
    ports:
      - "3306:3306" 
    volumes:
      - db_data:/var/lib/mysql  
    networks:
      - coffee-shop-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coffee-shop-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/coffee_shop_backend
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: Admin1
    ports:
      - '8080:8080'
    networks:
      - coffee-shop-net
