version: '3.8'

services:
  mysql:
    image: 'mysql:8.0'
    container_name: coffee-shop-db
    environment:
      - MYSQL_DATABASE=coffee-shop-backend
      - MYSQL_ROOT_PASSWORD=Admin2
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=Admin1
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - coffee-shop-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coffee-shop-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql 
      DB_PORT: 3307
      DB_DATABASE: coffee-shop-backend 
      DB_USER: myuser 
      DB_PASSWORD: Admin1 
    ports:
      - '3000:3000' 
    networks:
      - coffee-shop-net

volumes:
  db_data:

networks:
  coffee-shop-net: